application: consider-osu
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: src/static/css

- url: /js
  static_dir: src/static/js

- url: /fonts
  static_dir: src/static/fonts

- url: /ckeditor
  static_dir: src/static/ckeditor

- url: /admin
  script: src.consider.application
  login: admin
  auth_fail_action: redirect

- url: /.*
  script: src.consider.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
